routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

Route::get('/', 'HomeController@index')->name('home.index');

Route::group(['prefix' => 'admin'], function(){
    Auth::routes();
    
    Route::group(['middleware' => ['auth']], function () {
        // Route::get('dashboard', 'DashboardController@index')->defaults('_config',[
        //     'view'=>'admin.index'
        // ])->name('dashboard');

        Route::resource('form', 'FormsController');
        Route::post('form/checkunique', 'FormsController@checkunique')->name('form.unique');
        Route::resource('questions', 'QuestionController');
        Route::resource('submission', 'SubmissionController');
        Route::get('submission/export/{id}', 'SubmissionController@export')->name('submission.export');
        Route::get('submission/clear/{id}', 'SubmissionController@clearres')->name('submission.clear');
    });
});

Route::get('form/{link}', 'SurveyController@index')->name('survey.index');

Route::post('form/save', 'SurveyController@store')->name('survey.store');

Route::post('form/get', 'SurveyController@getans')->name('survey.get');

app/Http/Controllers/FormsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Form;
class FormsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data=array();
        $data['forms'] = Form::all()->reverse();
        $data['type']="create";
        return view('admin.forms.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
        $data=array();
        $data['type']="create";
        return view('admin.forms.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input=$request->all();
        $input['status']=trim($request->status);
        $form = Form::create($input);

        return redirect()->route('questions.index',['form_id'=>$form->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data=array();
        $data['type']="edit";
        $data['form'] = Form::find($id);
        return view('admin.forms.create',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input=$request->all();
        $form=Form::find($id);
        $form->name=$input['name'];
        $form->time=$input['time'];
        $form->link=$input['link'];
        $form->status=trim($input['status']);
        $form->save();
        if($form->users->where('status',1)->count()<1){
            return redirect()->route('questions.edit',[$form->id, 'backto'=>1]);
        }
        return redirect()->route('form.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Form::find($id)->delete();
        return redirect()->route('form.index');
    }

    public function checkunique(Request $request){
        return ['status' => !Form::where('link',$request->link)->first()];
    }
}

resources/views/admin/forms/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <span class="d-flex align-items-center">
                <a href="{{ route('form.index') }}"><i class="fas fa-arrow-left"></i></a>
                <h1 class="h3 mb-0 ml-2 text-gray-800"> @if($type=="create")Create @else Update @endif form</h1>
            </span>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4 step1">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
                    </div> <br>
                    <div class="card-body px-5">
                            @if ($type=="create")
                            {!! Form::open(['route' => 'form.store','method'=>'POST','id'=>'form_validate']) !!}
                          @else
                            {{ Form::model($form,['method' => 'PATCH', 'route' =>['form.update',$form->id],'id'=>'form_validate'] ) }}
                          @endif
                            <div class="col-md-6 mx-auto column">
                                <div class="form-group">
                                    <label for="form_name"><strong>Form name:</strong></label>
                                    {!! Form::text('name',null,['class'=>'form-control','id'=>'form_name']) !!}
                                </div>
                                <div class="form-group">
                                    <label for="form_timer"><strong>Timer(minutes):</strong></label>
                                    {!! Form::number('time',null,['class'=>'form-control','id'=>'form_timer']) !!}
                                </div>

                                <div class="form-group">
                                    <label for="form_link"><strong>URL Link:</strong></label>
                                    <span class="d-flex align-items-start">
                                        <span class="border rounded-left" style="padding:6px 5px;">{{\URL::to('/')}}/form/</span>
                                        <span style="width: 100%;">
                                            {!! Form::text('link',null,['class'=>'form-control','id'=>'form_link']) !!}
                                        </span>
                                    </span>
                                </div>
                                <div class="form-group d-flex align-items-center toggle_form_status" >
                                    <label for="message-text" class="col-form-label">Status:</label>
                                    <input type="hidden" value="@if(isset($form)) {{$form->status}} @else 1 @endif" name="status" id="form_status">
                                    <a href="#" class="text-primary ml-1 d-flex" style="font-size: 1.2rem;"><i class="fas fa-toggle-{{ ([1=>'on',0=>'off'][$form->status ?? 1])}}"></i></a>
                                </div>
                                <button type="submit" class="btn btn-primary float-right"> @if($type=="create")Create @else Update @endif</button>
                                <a href="{{route('form.index')}}" class="btn btn-primary float-right mr-2">Back</a>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push("scripts")
    <link rel="stylesheet" href="{{asset('css/create-form.css')}}">
    <script type="text/javascript">
        $(function(){
            let create = @if($type=="create")true @else false @endif;
            $('body').on('click', '.toggle_form_status>a', function(e){
                let ele = $(this).closest('.toggle_form_status');
                const toggle_value = ele.find('#form_status');
                const toggle_style = ele.find('i');
                stat = (toggle_value.val()==0)?1:0;
                toggle_value.val(stat);
                if(stat==1){
                    toggle_style.removeClass('fa-toggle-off').addClass('fa-toggle-on');
                }else if(stat==0){
                    toggle_style.removeClass('fa-toggle-on').addClass('fa-toggle-off');
                }
                e.preventDefault();
            });

            $('body').on('submit', '#form_validate', function(e){
                e.preventDefault();
                var this_form = $(this);
                $('.err_form').remove();
                let validate = true;
                $(this).find('input, textarea').each(function(){
                    if(!($(this).val())){
                        validate = false;
                        $(this).after('<span class="text-danger err_form">This field is required</span>');
                    }
                });

                let ele = $(this).find('#form_link');
                let link = ele.val();

                if(create){
                    $.ajax({
                        url:"{{route('form.unique')}}",
                        method:'POST',
                        data:{
                            "_token": "{{ csrf_token() }}",
                            "link":link,
                        },
                        success:function(res){
                            if(!res['status']){
                                ele.after('<span class="text-danger err_form">Link already used!</span>');
                            }else if(validate == true){
                                this_form.unbind(e);
                                this_form.submit();
                            }
                        }
                    });
                }else{
                    if(validate == true){
                        this_form.unbind(e);
                        this_form.submit();
                    }
                }
            });
        });
    </script>
@endpush

resources/views/admin/forms/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Manage Forms</h1>
            <a href="{{route('form.create')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus"></i> Create Form</a>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div
                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Forms</h6>
                    </div>
                    <div class="card-body">

                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Time(minutes)</th>
                                        <th>Link</th>
                                        <th>Submits Count</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Name</th>
                                        <th>Time</th>
                                        <th>Link</th>
                                        <th>Submits Count</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach($forms ?? [] as $form)
                                    <tr>
                                        <td>{{$form->name}}</td>
                                        <td>{{$form->time}}</td>
                                        <td>
                                            <span>{{\URL::to('/')}}/form/{{$form->link}}</span>
                                            <span class="fa fa-clone btn-copy" aria-hidden="true" data-clipboard-text="{{\URL::to('/')}}/form/{{$form->link}}"></span>
                                        </td>
                                        <td>{{$form->users->where('status',1)->count()}}</td>
                                        <td>{{[0=>"Deactive", 1=>"Active"][$form->status] ?? 'Unknown'}}</td>
                                        <td class="d-flex flex-column align-items-center">
                                            <a href="{{route('form.edit',[$form->id])}}" class="btn btn-primary btn-sm mb-2"><i class="fas fa-cog"></i> Edit Form</a>
                                            <a href="#" class="btn btn-danger btn-sm mb-2 delete_method" data-url="{{route('form.destroy',[$form->id])}}"><i class="fas fa-trash-alt"></i> Delete Form</a>
                                            @if($form->users->where('status',1)->count()<1)
                                                <a href="{{route('questions.edit',$form->id)}}" class="btn btn-primary mb-2 btn-sm"><i class="fas fa-edit"></i> Edit Questions </a>
                                            @else
                                                <a href="{{route('submission.index',['form'=>$form->id])}}" class="btn btn-primary mb-2 btn-sm"><i class="fas fa-comments"></i> Responses </a>
                                                <a href="{{route('submission.clear',['form'=>$form->id])}}" class="btn btn-primary mb-2 btn-sm delete_response"><i class="fas fa-trash-alt"></i> Delete Response </a>
                                            @endif
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{asset('js/manage-forms.js')}}"></script>
    <style>
        td a{
            width:150px ;
        }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.8/clipboard.min.js"></script>
    <script>
        $(function(){

            $('#dataTable').DataTable({
                "autoWidth": false,
                "bSort" : false
            });

            $('.delete_response').click(function(e){
                if(!confirm('Do you like to delete responses?')){
                    e.preventDefault();
                }
            });

            $('.delete_method').click(function(){
                if(confirm('Do you like to delete this form?')){
                    $.ajax({
                        url:$(this).data('url'),
                        method:"POST",
                        data:{
                            "_method":"DELETE",
                            '_token':'{{csrf_token()}}'
                        },
                        success:function(){
                            location.reload();
                        }
                    });
                }                
            });

            const afterCopy = function(e){
            var target = $(e.trigger);
            $(e.trigger).append($('<span class="copied-tip">Copied</span>').hide().fadeIn(100));
                setTimeout(function(){
                    target.find('.copied-tip').fadeOut(200, function(){$(this).remove()});
                },2000);
            }

            var clipboard1 = new ClipboardJS('.btn-copy');

            clipboard1.on('success', afterCopy);
        })

    </script>
     <style type="text/css">
        .btn-copy, .inv-copy{
            cursor: pointer;
            display: inline-block;
            margin-left: 5px;
            color: #0995CD;
            position: relative;
        }

        .copied-tip{
            position: absolute;
            font-size: .8rem;
            padding: 6px 9px;
            top: -29px;
            color: #EEE;
            left: 50%;
            transform: translateX(-50%);
            background-color: rgba(0, 0, 0,.7);
            font-family: arial, sans-serif;
            border-radius: 3px;
            z-index: 1000;
            box-shadow: 1.5px 1.5px 2px rgba(0, 0, 0, .3);
        }
    </style>
@endpush